service:
  port:
    name: http
    l4_protocol: TCP
    port: 80
    targetPort: 80
  label: frontend-service-1-4kesiq8at2
  name: frontend-service-1-4kesiq8at2
  selector: frontend-service-1-4kesiq8at2
  type:
  - ClusterIP
  - NodePort
namespace: test-dev
pvc:
  name: pvc-frontend-service-1-4kesiq8at2
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: frontend-service-1-4kesiq8at2
    type: react
  replicas: 2
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: frontend-service-1-4kesiq8at2
    tag: 7777-4574-frontend-service-1-4kesiq8at2-3149c51
    secret: regsecret
  container:
    name: frontend-service-1-4kesiq8at2
    port: 80
  volume:
    name: pvc-frontend-service-1-4kesiq8at2
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-frontend-service-1-4kesiq8at2
    minReplicas: 1
    maxReplicas: 2
    cpu: 70
    memory: -@memAutoScale@-
